stages:
  - publish

helm:
  stage: publish
  image:
    name: alpine/helm:4.1.1
    entrypoint: ["/bin/sh", "-c"]
  rules:
    - if: '$CI_MERGE_REQUEST_ID'
      changes:
        - devopscoop/**/*
        - pipeline.sh
        - .gitlab-ci.yml
      when: always
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes:
        - devopscoop/**/*
        - pipeline.sh
        - .gitlab-ci.yml
      when: always
    - when: never
  script:
    - export helm_registry="registry.gitlab.com"
    - export helm_username="$CI_REGISTRY_USER"
    - export helm_password="$CI_REGISTRY_PASSWORD"
    - export registry_namespace="$CI_PROJECT_PATH"
    - |
      if [ -n "$CI_MERGE_REQUEST_ID" ]; then
        ./pipeline.sh push-rc
      else
        ./pipeline.sh push
      fi
