# Maybe we should aspire to use this pipeline?
# https://gitlab.com/gitlab-org/charts/gitlab-runner/-/blob/main/.gitlab-ci.yml?ref_type=heads

image: registry.gitlab.com/dedevsecops/workstation:aws

deploy:
  script:
    - >
      helm repo add dedevsecops --username "$CHARTMUSEUM_USR" --password "$CHARTMUSEUM_PSW" https://charts.dedevsecops.com
      for chart in dedevsecops/*; do
        if helm lint "${chart}"; then
          # Never fail...
          helm push "${chart}" dedevsecops || true
        fi 
      done
