apiVersion: v2
name: app
description: A generic, reusable application chart for Kubernetes — extends the default helm create with StatefulSet, Gateway API, multiple env injection patterns, and more.
home: https://gitlab.com/devopscoop/charts
icon: https://gitlab.com/devopscoop/charts/-/raw/main/devopscoop/app/icon.png
keywords:
  - app
  - application
  - deployment
  - statefulset
  - web
sources:
  - https://gitlab.com/devopscoop/charts
  - https://github.com/devopscoop/charts
  - https://codeberg.org/devopscoop/charts
type: application
version: 0.11.0
appVersion: "1.16.0"
kubeVersion: ">=1.19.0"
maintainers:
  - name: devopscoop
    url: https://devops.coop
